'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fibNums():
	num1 = 1
	num2 = 2
	evensSum = 0
	while (num2 < 4000000):
		if (num2 % 2 == 0):
			evensSum += num2
		temp = num1
		num1 = num2
		# print "old num2 is " + str(num2)
		num2 = num1 + temp
		# print "new num2 is " + str(num2)
	return evensSum

print fibNums()